---
title: "statistical inference"
author: "Renukaneeli"
date: "6/2/2021"
output: pdf_document
---

```{r}
lambda <- 0.2
n <- 40
sims <- 1:1000
set.seed(123)

# Check for missing dependencies and load necessary R packages
if(!require(ggplot2)){install.packages('ggplot2')}; library(ggplot2)

# Simulate the population
population <- data.frame(x=sapply(sims, function(x) {mean(rexp(n, lambda))}))

# Plot the histogram
hist.pop <- ggplot(population, aes(x=x)) + 
  geom_histogram(aes(y=..count.., fill=..count..)) +
  labs(title="Histogram for Averages of 40 Exponentials over 1000 Simulations", y="Frequency", x="Mean")
hist.pop
```

# Tabulating the Sample Mean & Theoretical Mean

```{r}
sample.mean <- mean(population$x)
theoretical.mean <- 1/lambda
cbind(sample.mean, theoretical.mean)
```

# Checking 95% confidence interval for Sample Mean
```{r}
t.test(population$x)[4]
```

# 1.4. Sample Variance versus Theoretical Variance
# As we can see below both Sample Variance and Theoretical Variance are very close.

```{r}
sample.variance <- var(population$x)
theoretical.variance <- ((1/lambda)^2)/n
cbind(sample.variance, theoretical.variance)
```

# Plotting Sample Mean & Varience vs Theoretical Mean & Varience
```{r}
gg <- ggplot(population, aes(x=x)) +
  geom_histogram(aes(y=..density.., fill=..density..)) +
  labs(title="Histogram of Averages of 40 Exponentials over 1000 Simulations", y="Density", x="Mean") + 
  geom_density(colour="blue") +
  geom_vline(xintercept=sample.mean, colour="blue", linetype="dashed") +
  stat_function(fun=dnorm,args=list( mean=1/lambda, sd=sqrt(theoretical.variance)),color = "red") +
  geom_vline(xintercept=theoretical.mean, colour="red", linetype="dashed") 
gg
```

